### ISSUE TITLE
How to add benchmark

### ISSUE THREAD

**Issue by karussell** [tzaeschke/TinSpin#1]
How would I add a benchmark e.g. for our [LocationIndexTree](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/storage/index/LocationIndexTree.java) (memory efficient quadtree)?

And I did not see any code to warm up the JVM is this considered? Or maybe you can have a look into [JMH](http://openjdk.java.net/projects/code-tools/jmh/)?

**Comment by tzaeschke** [comment]
> How would I add a benchmark e.g. for our LocationIndexTree (memory efficient quadtree)?

Have a look at the classes in `ch.ethz.glbis.tinspin.wrappers`, they are the wrapper classes for different indexes. There are separate wrappers for Point data and Rectangle Data.
Then, you need to register the new wrapper in `TestStats.IDX`. If you don't want to modify the Enum, you can use the generic 'IDX.CUSTOM' enum, see `AbstractWrapperTest` for an example  (just need to call `setCandidateClass()`).

Let me know if you get stuck.

> And I did not see any code to warm up the JVM is this considered? 

There are two types of warmup:

1. Each test is run twice, first with a dataset size of 100'000, then again with the full desired size. See `TestRunnerLocal.test(...)`.
2. Most loads (except insert and remove) are run twice, so the first run can be considered as warmup.

> Or maybe you can have a look into JMH?

I think JMH can be very useful for low level routines. However, an index is a more complex beast whose performance appears to mostly depend on the dataset (size, dimensionality, distribution) and environment (type of machine, primary loads). I found that the bottleneck is usually the amount of data and operations that need to be processed (which both depend on the general algorithm), while low-level optimization tend to have negligible effect on overall performance, except in rare cases. Did you have something in mind related to JMH?

**Comment by tzaeschke** [comment]
Btw, if you don't want to run the full suite: I usually do preliminary testing by directly running the `TestRunner`.

**Comment by karussell** [comment]
Thanks, will try!

> Did you have something in mind related to JMH?

No. Just wanted to point to a framework for benchmarking, but likely you coded something simple enough to replace it (like we do for our stuff :))

**Comment by tzaeschke** [comment]
Just in case this is still of interest, TinSpin has been refactored to simplify integration of custom indexes and datasources. See [TinSpin/src/main/java/ch/ethz/globis/tinspin/Example.java](https://github.com/tzaeschke/TinSpin/blob/master/src/main/java/ch/ethz/globis/tinspin/Example.java) for an example.
